### PR TITLE
Symlink bei Uninstall entfernen

### PR DESCRIPTION
**Pull request by uwe111**

### CODE REVIEW

**Comment by ultrah** [comment]
@hobbyquaker merge? :)

**Comment by jens-maus** [comment]
@hobbyquaker 
It seems that it is really time that you finally merge that pull request. So please do so!

**Comment by jens-maus** [comment]
please note that I have just created an own pull request at https://github.com/hobbyquaker/XML-API/pull/2 which also integrates the changes suggested here but in addition makes xml-api add-on compatible to RaspberryMatic (HM-RASPBERRYMATIC).

**Comment by ultrah** [comment]
#2 fixes this, so no need to merge this

**Pull request closed without merging**
